apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workshops.training.eduk8s.io
spec:
  group: training.eduk8s.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
              - vendor
              - title
              - description
              - url
              - image
              properties:
                vendor:
                  type: string
                title:
                  type: string
                description:
                  type: string
                url:
                  type: string
                image:
                  type: string
                timeout:
                  type: string
                  pattern: '^\d+(s|m|h)$'
                duration:
                  type: string
                  pattern: '^\d+(s|m|h)$'
                deployment:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                spawnerNamespace:
                  type: object
                  properties:
                    objects:
                      type: array
                      items:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                sessionNamespace:
                  type: object
                  properties:
                    role:
                      type: string
                    budget:
                      type: string
                    objects:
                      type: array
                      items:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                enabled:
                  type: boolean
                  default: false
      additionalPrinterColumns:
      - name: Image
        type: string
        priority: 0
        description: The location of the image for the workshop.
        jsonPath: .spec.image
      - name: URL
        type: string
        priority: 1
        description: URL for further information on the workshop.
        jsonPath: .spec.url
      - name: Enabled
        type: boolean
        priority: 0
        description: Whether the workshop can be deployed.
        jsonPath: .status.enabled
  scope: Cluster
  names:
    plural: workshops
    singular: workshop
    kind: Workshop
